package com.E8908.db;

public class DaoQueryBean {
    public int id;//主健
    public String beforeWpbfScore;//施工前物品摆放分值
    public String beforeWpbfPicUrl;//施工前物品摆放图片URL
    public String afterWpbfScore;//施工后物品摆放分值
    public String afterWpbfPicUrl;//施工后物品摆放图片URL
    public String beforeKqlxScore;//施工前空调滤芯洁净度分值
    public String beforeKqlxPicUrl;//施工前空调滤芯洁净度图片URL
    public String afterKqlxScore;//施工后空调滤芯洁净度分值
    public String afterKqlxPicUrl;//施工后空调滤芯洁净度图片URL
    public String beforeCnfcwrScore;//施工前车内粉法污染分值
    public String beforeCnfcwrPicUrl;//施工前车内粉法污染图片URL
    public String afterCnfcwrScore;//施工后车内粉法污染分值
    public String afterCnfcwrPicUrl;//施工后车内粉法污染图片URL
    public String beforeXdsjScore;//施工前消毒杀菌分值
    public String beforeXdsjPicUrl;//施工前消毒杀菌图片URL
    public String afterXdsjScore;//施工后消毒杀菌分值
    public String afterXdsjPicUrl;//施工后消毒杀菌图片URL
    public String beforeSwczScore;//施工前食物残渣分值
    public String beforeSwczPicUrl;//施工前食物残渣图片URL
    public String afterSwczScore;//施工后食物残渣分值
    public String afterSwczPicUrl;//施工后食物残渣图片URL
    public String beforeKqjhScore;//施工前空气净化分值
    public String beforeKqjhPicUrl;//施工前空气净化图片URL
    public String afterKqjhScore;//施工后空气净化分值
    public String afterKqjhPicUrl;//施工后空气净化图片URL
    public String beforeNsjjdScore;//施工前内饰洁净度分值
    public String beforeNsjjdPicUrl;//施工前内饰洁净度图片URL
    public String afterNsjjdScore;//施工后内饰洁净度分值
    public String afterNsjjdPicUrl;//施工后内饰洁净度图片URL
    public String beforeCnjxScore;//施工前车内清洗分值
    public String beforeCnjxPicUrl;//施工前车内清洗图片URL
    public String afterCnjxScore;//施工后车内清洗分值
    public String afterCnjxPicUrl;//施工后车内清洗图片URL
    public String beforeLxbmwgScore;//施工前空调滤芯表面污圬分值
    public String beforeLxbmwgPicUrl;//施工前空调滤芯表面污圬图片URL
    public String afterLxbmwgScore;//施工后空调滤芯表面污圬分值
    public String afterLxbmwgPicUrl;//施工后空调滤芯表面污圬图片URL
    public String beforeZfxbmwgScore;//施工前蒸发箱表面污垢分值
    public String beforeZfxbmwgPicUrl;//施工前蒸发箱表面污垢图片URL
    public String afterZfxbmwgScore;//施工后蒸发箱表面污垢分值
    public String afterZfxbmwgPicUrl;//施工后蒸发箱表面污垢图片URL
    public String beforeGfjbmwgScore;//施工前鼓风机表面污垢分值
    public String beforeGfjbmwgPicUrl;//施工前鼓风机表面污垢图片URL
    public String afterGfjbmwgScore;//施工后鼓风机表面污垢分值
    public String afterGfjbmwgPicUrl;//施工后鼓风机表面污垢图片URL
    public String beforeTfgdbmwgScore;//施工前通风管道表面污垢分值
    public String beforeTfgdbmwgPicUrl;//施工前通风管道表面污垢图片URL
    public String afterTfgdbmwgScore;//施工后通风管道表面污垢分值
    public String afterTfgdbmwgPicUrl;//施工后通风管道表面污垢图片URL
    public String beforeLnqbmwgScore;//施工前冷凝器表页污垢分值
    public String beforeLnqbmwgPicUrl;//施工前通风管道表面污垢图片URL
    public String afterLnqbmwgScore;//施工后冷凝器表页污垢分值
    public String afterLnqbmwgPicUrl;//施工后冷凝器表页污垢图片URL
    public String beforeKtxtzlxnScore;//施工前空调系统制令性能分值
    public String beforeKtxtzlxnPicUrl;//施工前空调系统制令性能图片URL
    public String afterKtxtzlxnScore;//施工后空调系统制令性能分值
    public String afterKtxtzlxnPicUrl;//施工后空调系统制令性能图片URL
    public String beforeKtkqyxScore;//施工前开启空调时异响分值
    public String beforeKtkqyxPicUrl;//施工前开启空调时异响图片URL
    public String afterKtkqyxScore;//施工后开启空调时异响分值
    public String afterKtkqyxPicUrl;//施工后开启空调时异响图片URL

    public String beforeCfkyw;//施工前出风口异味分值
    public String afterCfkyw;//施工后出风口异味分值
    public String beforeScwpyw;//施工前随车物品异味分值
    public String afterScwpyw;//施工后随车物品异味分值
    public String beforeXcyw;//施工前新车异味分值
    public String afterXcyw;//施工后新车异味分值
    public String beforeEsyyw;//施工前二手烟异味分值
    public String afterEsyyw;//施工后二手烟异味分值
    public String beforeNspgyw;//施工前内饰皮革异味分值
    public String afterNspgyw;//施工后内饰皮革异味分值
    public String beforeXjmbyw;//施工前细菌霉变异味分值
    public String afterXjmbyw;//施工后细菌霉变异味分值
    public String beforeNsxfyw;//施工前内饰吸附异味分值
    public String afterNsxfyw;//施工后内饰吸附异味分值
    public String beforeQtyw;//施工前其它异味分值
    public String afterQtyw;//施工后其它异味分值
    public String beforeJq;//施工前甲醛数值
    public String afterJq;//施工后甲醛数值
    public String beforeTvoc;//施工前tvoc数值
    public String afterTvoc;//施工后tvoc数值
    public String beforePm25;//施工前PM2.5数值
    public String afterPm25;//施工后PM2.5数值
    public String beforeWd;//施工前温度数值
    public String afterWd;//施工后温度数值
    public String beforeSd;//施工前湿度数值
    public String afterSd;//施工后显度数值

    public String carNumber;

}
